### ISSUE TITLE
Change Alignment Event, Paint Logic, Game and window counter

### ISSUE THREAD

**Issue by Jinx1994** [DevPhilB/Introduction_2_6#2]
Change Alignment Event is not working properly
Paint logic is still buggy: you can only change the colors of view and not for the whole game
Game and window counter is also buggy when you start a new game

**Comment by DevPhilB** [comment]
> Change Alignment Event is not working properly
How should it works?
> Paint logic is still buggy: you can only change the colors of view and not for the whole game
Read third point in requirement list!
> Game and window counter is also buggy when you start a new game
Check values/counter logic!
And prevent empty user inputs (maybe with default values) for Rows/Columns

**Comment by Jinx1994** [comment]
Change Alignment: swapping amount of rows and columns with eacht other
Example: row: 10 column 5 --> row: 5 column:10
